### PR TITLE
Create about section

### PR DESCRIPTION
**Pull request by wellnahuel**
## Description
Create the about section.
Add new photos.
Create 2 new components, infocard and bigInfoCard to be reusable throughout the site.
Add jsdoc to the new components.
The entire about section is responsive.

## How to test?
npm run dev

### CODE REVIEW

**Review by Azrux — CHANGES_REQUESTED** [review]
Hey, it looks nice. I love it ❤️

A few details:
* Check the responsive design. On small screens, some texts don't display properly.
image

* Same for these tags:
image

* All the pages were using "Argentinian Spanish," for example: "Unite al Club Athenas" or "Descubrí lo mejor del deporte y la comunidad." However, you used a more neutral Spanish, like: "Únete a nuestra comunidad." We need to decide on the type of Spanish we want to use. I chose the "Vos" form since we're all Argentinian, but I don't mind using "Tú." Let me know what you think.

**Comment by wellnahuel** [comment]
> Hey, it looks nice. I love it ❤️
> 
> A few details:
> 
> * Check the responsive design. On small screens, some texts don't display properly.
>   image
> * Same for these tags:
>   image
> * All the pages were using "Argentinian Spanish," for example: "Unite al Club Athenas" or "Descubrí lo mejor del deporte y la comunidad." However, you used a more neutral Spanish, like: "Únete a nuestra comunidad." We need to decide on the type of Spanish we want to use. I chose the "Vos" form since we're all Argentinian, but I don't mind using "Tú." Let me know what you think.

image

**Comment by wellnahuel** [comment]
> > Hey, it looks nice. I love it ❤️
> > A few details:
> > 
> > * Check the responsive design. On small screens, some texts don't display properly.
> >   image
> > * Same for these tags:
> >   image
> > * All the pages were using "Argentinian Spanish," for example: "Unite al Club Athenas" or "Descubrí lo mejor del deporte y la comunidad." However, you used a more neutral Spanish, like: "Únete a nuestra comunidad." We need to decide on the type of Spanish we want to use. I chose the "Vos" form since we're all Argentinian, but I don't mind using "Tú." Let me know what you think.
> 
> image

image

**Review by Azrux — APPROVED** [review]
LGTM 😊

**Pull request merged**
